public without sharing class LT_Constants {
    public static final String PRODUCT_FAMILY_TRUCK = 'Truck';
    public static final String NO_DATA = 'N/A';
    public static final String MULESOFT_INTEGRATION_SETTINGS = 'Mulesoft_Integration_Settings';
    public static final String CLIENT_ID = 'client-id';
    public static final String CLIENT_SECRET = 'client-secret';
    public static final String CORRELATION_ID = 'correlation-id';
    public static final String GET = 'GET';
}